### ISSUE TITLE
Functions returning only first return value

### ISSUE THREAD

**Issue by kolyasapphire** [banteg/multicall.py#2] opened 2021-01-19 11:07 UTC
Hi!

I was wondering if I'm missing something or functions are not returning all return values using `Multicall([Call()])`.

Example call:

```
Multicall(
            [
                Call(
                    address,
                    [
                        "my_function(uint256,uint256)(bytes,bytes,bytes)",
                        argument_1,
                        argument_2,
                    ],
                    [[i, None]],
                )
                for i in range(99)
            ]
)
```

I was able to fix this for my use case by changing `decoded` to `[decoded]` here:

https://github.com/banteg/multicall.py/blob/089b39067d8e8773706a01be3a774e24ab2f8dfb/multicall/call.py#L27

If it's indeed a bug, I would be happy to test my solution and submit a PR.

**Comment by VensonLiou** [comment] 2022-01-06 18:46
Same issue here and solved with the solution by @kolyasapphire .

**Comment by MihaZelnik** [comment] 2022-02-25 09:36
@banteg what do you thing? I also have issues with not returning multiple values

**Comment by BobTheBuidler** [comment] 2022-03-21 15:38
Using the current master branch, I don't have any issue returning multiple values. @MihaZelnik, if you upgrade the package, do you still have issues with this?

**Comment by BobTheBuidler** [comment] 2022-03-29 07:22
In case anyone else has issues returning multiple values and stumbles across this thread...
Make sure you encode the return values like so:
yes - someFunction()((dtype,dtype))
no - someFunction()(dtype,dtype)

Closing this issue as the library is confirmed to work as intended.

**Closed by BobTheBuidler** 2022-03-29 07:22 UTC

**Comment by MihaZelnik** [comment] 2022-03-29 07:41
@BobTheBuidler perfect, thank you!
